### PR TITLE
fix: disable unintended parallel processing in sumcheck stage 1

### LINKED ISSUE #511: Sumcheck prover hang
You can reproduce this issue by running cmd in the branch of #368.
```
RAYON_NUM_THREADS=64 RUST_LOG=debug cargo run --release --example fibonacci_elf -- --nocapture
```

The prover hangs when it's running the main selector sumcheck for `SLLI` opcode with `num_instances = 650`.

Last few logs on my machine
```
2024-10-31T09:41:55.584326Z DEBUG sumcheck::tower: ceno_zkvm::scheme::prover: generated tower proof at round 13/13
2024-10-31T09:41:55.589190Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 1/7
2024-10-31T09:41:55.589970Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 1/7
2024-10-31T09:41:55.594713Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 2/7
2024-10-31T09:41:55.596938Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 2/7
2024-10-31T09:41:55.600338Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 3/7
2024-10-31T09:41:55.605352Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 3/7
2024-10-31T09:41:55.610686Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 4/7
2024-10-31T09:41:55.610927Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 4/7
2024-10-31T09:41:55.618196Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 5/7
2024-10-31T09:41:55.619944Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 5/7
2024-10-31T09:41:55.627636Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 6/7
2024-10-31T09:41:55.627888Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 6/7
2024-10-31T09:41:55.632615Z DEBUG prove_rounds: sumcheck::prover_v2: thread 1: sumcheck round 7/7
2024-10-31T09:41:55.634330Z DEBUG prove_rounds: sumcheck::prover_v2: thread 0: sumcheck round 7/7
2024-10-31T09:41:55.642064Z DEBUG ceno_zkvm::scheme::prover: tower sumcheck finished
2024-10-31T09:41:55.645229Z DEBUG sumcheck::main_sel: ceno_zkvm::scheme::prover: main sel sumcheck start
```

### PR DESCRIPTION
**Pull request by hero78119**
Fixed #511

### Root cause
We have 2 stage sumcheck
- stage 1: each rayon job isolated processing 
- stage 2: single thread aggregate results.

So in stage 1,  a rayon job shouldn't invoke parallel rayon internally, otherwise it will invoke deadlock, since there is 0 rayon idle thread in pool, so the parallel job will hang and never generate 1st round of univariate evaluation, so the main worker thread never get enough message to processing.

This only happened when `extrapolate`  was invoked on the situation when virtual polynomial got different degree monomial terms. In other word, it tend to happened on opcodes with different degree of monomial terms in a constrain.

The fix is we need to have stage 1 strictly serialized and do not invoke rayon parallel internally.

### Another minor optimisation
Previously main thread also be one of worker thread, thus it also exchange data via channel which might incur a unnecessary cost. This PR also remove this cost and exchange data locally.

### Testing
- cherry-pick commit into PR #368 and doen't hang anymore on `ceno-server`, previously with command `RAYON_NUM_THREADS=64 RUST_LOG=debug cargo run --release --example fibonacci_elf -- --nocapture` it's 100% reproduce
- before/after the change benchmark on 2^20 instances add remain the same, which is expected since there is no constrain in add opcode which got different degree monomial terms.

### CODE REVIEW

**Comment by matthiasgoergens** [comment]
Thanks for the detailed PR description.!

File: sumcheck/src/util.rs [hunk 1]
```diff
@@ -98,9 +103,31 @@ fn serial_batch_inversion_and_mul<F: PrimeField>(v: &mut [F], coeff: &F) {
...
+    points: &[F],
+    weights: &[F],
+    evals: &[F],
+    at: &F,
+) -> F {
     let (coeffs, sum_inv) = {
         let mut coeffs = points.iter().map(|point| *at - point).collect::<Vec<_>>();
-        batch_inversion(&mut coeffs);
+        if IS_PARALLEL {
+            batch_inversion(&mut coeffs);
```
Comment (matthiasgoergens) [inline sumcheck/src/util.rs:127]: Have we actually ever run any benchmarks to see whether parallel batch inversion helps us?

Comment (matthiasgoergens) [reply sumcheck/src/util.rs:127]: Update: I just rigged up some benchmarks, and we do get a speedup here.  At least when doing a (batch) single inversion at a time (of eg `1<<20` field elements.)

File: sumcheck/src/prover_v2.rs [hunk 2]
```diff
@@ -131,9 +133,8 @@ impl<'a, E: ExtensionField> IOPProverStateV2<'a, E> {
             }
 
             let mut prover_msgs = Vec::with_capacity(num_variables);
-            let thread_id = max_thread_id - 1;
             let mut prover_state = Self::prover_init_with_extrapolation_aux(
-                mem::take(&mut polys[thread_id]),
```
Comment (matthiasgoergens) [inline sumcheck/src/prover_v2.rs:136]: Treating the last polynomial different seems a bit weird to me.  I wonder if we can find a better way to organise the threads.  (But this PR isn't making things worse, so it's fine.)

File: sumcheck/src/prover_v2.rs [hunk 3]
```diff
@@ -131,9 +133,8 @@ impl<'a, E: ExtensionField> IOPProverStateV2<'a, E> {
...
+                mem::take(&mut polys[main_thread_id]),
```
Comment (matthiasgoergens) [inline sumcheck/src/prover_v2.rs:137]: I highly approve of the rename.  Much less confusing.

**Review by matthiasgoergens — APPROVED** [review]
Thanks for fixing this!

**Comment by hero78119** [comment]
Hey @kunxian-xia originally I planned to merge this to master, but I believe you want to narrow down integration test debug scope in this period, so you might avoid having regular sync with master to your branch, also cherry pick might also troublesome.

how about we merge this PR to integration test feature branch instead? I'm fine with this plan :)

**Comment by kunxian-xia** [comment]
> how about we merge this PR to integration test feature branch instead? I'm fine with this plan :)

Sounds good to me!

**Comment by hero78119** [comment]
> > how about we merge this PR to integration test feature branch instead? I'm fine with this plan :)
> 
> Sounds good to me!

Ok done 👍

**Comment by naure** [comment]
Could we have this in master as well?
